export const skills = [
 {name:'Python',icon:'Py',type:'LANGUAGE',group:'Code',description:'A general-purpose programming language for scripts, apps and data work. Also a snake—this one runs code.',use:'Fingertip-to-drone controls and mathematical-model inference.',projects:[{name:'CoDrone Controller',url:'https://github.com/TacoGod900/codrone-edu-controller'},{name:'Kaggle',url:'https://github.com/TacoGod900/kaggle'}]},
 {name:'TypeScript',icon:'TS',type:'LANGUAGE',group:'Code',description:'JavaScript with a type system that helps catch mismatched data before the app runs.',use:'Screen state, settings and reusable menu components in this portfolio.',projects:[{name:'HG Portfolio',url:''}]},
 {name:'HTML & CSS',icon:'<>',type:'WEB',group:'Code',description:'HTML gives a page its structure; CSS controls its layout, colour and presentation.',use:'The inventory layout, animated transitions and responsive portfolio stage.',projects:[{name:'HG Portfolio',url:''}]},
 {name:'Svelte',icon:'Sv',type:'FRAMEWORK',group:'Code',description:'A component framework that connects an interface to changing application state.',use:'Reactive settings, skill selection and reusable menu components.',projects:[{name:'HG Portfolio',url:''}]},
 {name:'Scratch',icon:'Sc',type:'VISUAL LANGUAGE',group:'Code',description:'A block-based programming environment for learning through interactive projects.',use:'The Scratch project in my public CS50 repository.',projects:[{name:'CS50',url:'https://github.com/TacoGod900/cs50'}]},
 {name:'OpenCV',icon:'CV',type:'COMPUTER VISION',group:'Data',description:'A computer-vision library for reading, transforming and analysing images and video.',use:'Camera frames and visual feedback for the fingertip drone controller.',projects:[{name:'CoDrone Controller',url:'https://github.com/TacoGod900/codrone-edu-controller'}]},
 {name:'MediaPipe',icon:'MP',type:'HAND TRACKING',group:'Data',description:'Tools for finding structured landmarks—such as fingertips—in camera input.',use:'Hand landmarks, fingertip control zones and pinch gestures.',projects:[{name:'CoDrone Controller',url:'https://github.com/TacoGod900/codrone-edu-controller'}]},
 {name:'PyTorch',icon:'PT',type:'MACHINE LEARNING',group:'Data',description:'A tensor and machine-learning framework with GPU acceleration.',use:'CUDA checks and model inference in the mathematical-reasoning notebook.',projects:[{name:'Kaggle',url:'https://github.com/TacoGod900/kaggle'}]},
 {name:'Transformers',icon:'HF',type:'MODEL TOOLKIT',group:'Data',description:'A library for loading pretrained models and tokenizers and generating predictions.',use:'Loading Qwen2.5-Math and generating answers to competition problems.',projects:[{name:'Kaggle',url:'https://github.com/TacoGod900/kaggle'}]},
 {name:'pandas',icon:'pd',type:'DATA',group:'Data',description:'A Python library for working with tables, columns and structured datasets.',use:'Reading test problems and writing CSV and Parquet submissions.',projects:[{name:'Kaggle',url:'https://github.com/TacoGod900/kaggle'}]},
 {name:'Git & GitHub',icon:'Gt',type:'VERSION CONTROL',group:'Tools',description:'Git tracks changes to code; GitHub hosts repositories and collaboration.',use:'Versioned source and public project sharing.',projects:[{name:'GitHub profile',url:'https://github.com/TacoGod900'}]},
 {name:'SVG & animation',icon:'◇',type:'INTERFACE',group:'Tools',description:'Scalable vector graphics and timed transitions keep interfaces sharp and responsive.',use:'The menu’s text masks, selection shapes and animated chapter numbers.',projects:[{name:'HG Portfolio',url:''}]}
];
